version: '2'

services:
  epot-backend:
    container_name: epot-service
    image: node:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./:/epot/backend
    working_dir: /epot/backend
    depends_on:
      - arangodb
    command: yarn run dev
    env_file:
      - .env

  arangodb:
    container_name: epot-arangodb
    image: arangodb/arangodb
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=${DB_PASS}
      - ARANGO_STORAGE_ENGINE=rocksdb
    volumes:
      - ./docker/arangodb:/var/lib/arangodb3
    env_file:
      - .env
