version: '2'

services:
  arangodb:
    container_name: epot-arangodb
    image: arangodb/arangodb
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=${DB_PASS}
      - ARANGO_STORAGE_ENGINE=rocksdb
    volumes:
      - ./docker/arangodb:/var/lib/arangodb3
    env_file:
      - .env
